name = "aide_generator"
version = "0.4.0"

description = "Generate encoders and decoders for MCP tools "
licences = ["Apache-2.0"]
repository = { type = "github", user = "crowdhailer", repo = "aide_generator" }
links = []

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
glance = "< 4.0.0"
oas_generator = ">= 2.3.0 and < 3.0.0"
glance_printer = ">= 3.0.0 and < 4.0.0"
aide = ">= 0.7.0 and < 1.0.0"
castor = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
# blocked by versions of glance
birdie = ">= 1.2.7 and < 2.0.0"
