name = "aide_generator"
version = "0.1.0"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
# oas for json_schema
oas = ">= 7.2.0 and < 8.0.0"
glance = "< 4.0.0"
oas_generator = ">= 2.1.1 and < 3.0.0"
glance_printer = ">= 3.0.0 and < 4.0.0"
aide = ">= 0.5.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
# blocked by versions of glance
birdie = ">= 1.2.7 and < 2.0.0"
